apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: production
  namespace: metallb-system
spec:
  addresses:
  - 192.168.137.130-192.168.137.250 # specify the range of addresses
  autoAssign: true